In [44]:
#df = pd.DataFrame(result)
df = pd.read_csv('review_data.csv')
#df.to_csv('review_data.csv',sep=',', na_rep='NaN')
df.describe
df[['starScore','title']]

starScore                                              title
0             5  쑥 들어간 제품들을 평소에 좋아해서 쑥 화장품으로 대부분 쓰려고 해요 아침 저녁으로...
1             5  화장품 상자에 한번 더 뽁뽁이  포장으로  꼼꼼하게 담아져 있었고  화장품 용기는 ...
2             5  대용량에 헐 감동입니다 1개는 지인도 팍팍 쓰라고 선물했어요이건 화장솜에 듬뿍 하셔...
3             4  아직 사용전인데 오자마자 간병이모님이 머냐고 물어 보셔서 약쑥스킨이라고  하니 한번...
4             5  프레쥬 진정토너 여름에 시원하게 토너팩 하기 좋아요 향은 쑥 냄새보다는 시트러스계열...
...         ...                                                ...
9995          5                                       이번엔 제대로 왔어용!
9996          5                                         덩치가 큰게 좋네요
9997          5                                         좋아요~ 많이파세요
9998          3                                           빠름배송 좋아요
9999          5                                          잘받았습니다~^^

[10000 rows x 2 columns]

In [49]:
# cleasing 함수 
import regex as re
import numpy as np
def cleasing(text):
    repl =''
    pattern = '([ㄱ-ㅎㅏ-ㅣ]+)' # 자음, 모음 제거
    text = re.sub(pattern= pattern, repl=repl, string=text)
    #pattern = '[^\w\s]' # 특수기호 제거
    pattern = '[^가-히\s]' # 특수기호 제거
    text = re.sub(pattern= pattern, repl=repl, string=text)
    pattern = '<[^>]*>' # html 제거
    text = re.sub(pattern = pattern, repl='',string=text)
    return text
df['length'] = df.content.str.len()
df['label'] = np.where(df['starScore']<5, 0, 1)
df['clean_content'] = df['content'].map(lambda x: cleasing(x))
df2 = df[ df.length > 30 ] 
df2 = df2[['clean_content','label']]
df2[:10]

clean_content  label
0  쑥 들어간 제품들을 평소에 좋아해서 쑥 화장품으로 대부분 쓰려고 해요 아침 저녁으로...      1
1  화장품 상자에 한번 더 뽁뽁이  포장으로  꼼꼼하게 담아져 있었고  화장품 용기는 ...      1
2  대용량에 헐 감동입니다 개는 지인도 팍팍 쓰라고 선물했어요이건 화장솜에 듬뿍 하셔서...      1
3  아직 사용전인데 오자마자 간병이모님이 머냐고 물어 보셔서 약쑥스킨이라고  하니 한번...      0
4  프레쥬 진정토너 여름에 시원하게 토너팩 하기 좋아요 향은 쑥 냄새보다는 시트러스계열...      1
5  대이고 건성민감건성피부에  슬프면 앙대는데짐승용량착한가격부담없이 닥토스퇄마스크 트러...      1
6  다른분 말처럼 향이 강하네요발랐을때 깔끔한 느낌보다는 살짝 텁텁한 느낌이었어요 그렇...      0
7  스킨은 프레쥬만 써요작년에 접촉성 피부염으로 고생했을 때 연고고 레이저고 아무 소용...      1
8  닦토용으로 주문해 봤어요 저렴한데 가격대비 꽤 괜찮은것 같아요쑥향이 별로 안난다는 ...      1
9  쑥이라 해서 쑥 향이 나는 줄 알았지만 쑥향은 전혀 없고 보통 화장수의 향입니다엄청...      0

In [70]:
df2['check_content'] = ''
df2

clean_content  label check_content
0     쑥 들어간 제품들을 평소에 좋아해서 쑥 화장품으로 대부분 쓰려고 해요 아침 저녁으로...      1              
1     화장품 상자에 한번 더 뽁뽁이  포장으로  꼼꼼하게 담아져 있었고  화장품 용기는 ...      1              
2     대용량에 헐 감동입니다 개는 지인도 팍팍 쓰라고 선물했어요이건 화장솜에 듬뿍 하셔서...      1              
3     아직 사용전인데 오자마자 간병이모님이 머냐고 물어 보셔서 약쑥스킨이라고  하니 한번...      0              
4     프레쥬 진정토너 여름에 시원하게 토너팩 하기 좋아요 향은 쑥 냄새보다는 시트러스계열...      1              
...                                                 ...    ...           ...
9985  좋아요 재구맵니다 저번에는 유통기한 거의 다 된거 보내주셨는데 거의 다 쓰고 발견했...      0              
9986                            확실히 양도 많고 구성도 좋네요 만족합니다      1              
9987                               저렴한가격에  괜찮고좋습니다대박나셔요      1              
9990  잘 받았어요 잘 받았어요  아직 써보진 않았지만 기대됩니다 잘 쓰겠습니다 잘 받았어...      0              
9994  좋아요 대용량이라서 스킨팩하기에 너무 좋아요 개인차는 잇겟지만 향도 괜찮네요 정말 ...      0              

[4881 rows x 3 columns]

In [74]:
from py_hanspell.hanspell import spell_checker
check_result = []

for index, item in df2.iterrows():
    try:
        df2['check_content'][index] = spell_checker.check(item['clean_content']).checked
    except Exception as e: 
        print("error occur! : ",e)
        print(item['clean_content'])
        continue

df2[:10]

<ipython-input-74-b9cd282edc4b>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['check_content'][index] = spell_checker.check(item['clean_content']).checked
error occur! :  Invalid control character at: line 1 column 225 (char 224)
그부분만 조금 아쉬울뿐 용량는 짱짱걸


clean_content  label  \
0  쑥 들어간 제품들을 평소에 좋아해서 쑥 화장품으로 대부분 쓰려고 해요 아침 저녁으로...      1   
1  화장품 상자에 한번 더 뽁뽁이  포장으로  꼼꼼하게 담아져 있었고  화장품 용기는 ...      1   
2  대용량에 헐 감동입니다 개는 지인도 팍팍 쓰라고 선물했어요이건 화장솜에 듬뿍 하셔서...      1   
3  아직 사용전인데 오자마자 간병이모님이 머냐고 물어 보셔서 약쑥스킨이라고  하니 한번...      0   
4  프레쥬 진정토너 여름에 시원하게 토너팩 하기 좋아요 향은 쑥 냄새보다는 시트러스계열...      1   
5  대이고 건성민감건성피부에  슬프면 앙대는데짐승용량착한가격부담없이 닥토스퇄마스크 트러...      1   
6  다른분 말처럼 향이 강하네요발랐을때 깔끔한 느낌보다는 살짝 텁텁한 느낌이었어요 그렇...      0   
7  스킨은 프레쥬만 써요작년에 접촉성 피부염으로 고생했을 때 연고고 레이저고 아무 소용...      1   
8  닦토용으로 주문해 봤어요 저렴한데 가격대비 꽤 괜찮은것 같아요쑥향이 별로 안난다는 ...      1   
9  쑥이라 해서 쑥 향이 나는 줄 알았지만 쑥향은 전혀 없고 보통 화장수의 향입니다엄청...      0   

                                       check_content  
0  쑥 들어간 제품들을 평소에 좋아해서 쑥 화장품으로 대부분 쓰려고 해요 아침저녁으로 ...  
1  화장품 상자에 한 번 더 뽁뽁이  포장으로  꼼꼼하게 담아져 있었고  화장품 용기는...  
2  대용량에 헐 감동입니다 개는 지인도 팍팍 쓰라고 선물했어요이건 화장솜에 듬뿍하셔서 ...  
3  아직 사용 전인데 오자마자 간병 이모님이 머냐고 물어보셔서 약쑥 스킨이라고  하니 ...  
4  프레쥬 진정 토너 여름에 시원하게 토너 팩하기 좋아요 향은 쑥 냄새보다는 시트러스 ...  
5  대이고 건성 민감 건성피부에  슬프면 앙대는데 짐승 용량 착한 가격 부담 없이 닥토...  
6  다른 분 말처럼 향이 강하네요 발랐을 때 깔끔한 느낌보다는 살짝 텁텁한 느낌이었어요...  
7  스킨은 프레쥬만 써요 작년에 접촉성 피부염으로 고생했을 때 연고 고 레이 저고 아무...  
8  닦도 용으로 주문해 봤어요 저렴한데 가격 대비 꽤 괜찮은 것 같아요 쑥 향이 별로 ...  
9  쑥이라 해서 쑥 향이 나는 줄 알았지만 쑥 향은 전혀 없고 보통 화장수의 향입니다 ...

In [87]:
dataset_all = [ ['',0] for _ in range(len(df2)+1) ]
#print(dataset_all[0][0])
index = 0
for indexs, row in df2.iterrows():
    #print(index)
    dataset_all[index][0] = row['clean_content']
    dataset_all[index][1] = row['label']
    index = index+1

dataset_all[:5]

[['쑥 들어간 제품들을 평소에 좋아해서 쑥 화장품으로 대부분 쓰려고 해요 아침 저녁으로 매일 매일 쓰기에 부담이 없고 좋습니다자연약쑥 진정 토너라 자극없이 쓰기에도 좋고 녹차 루이보스 캐모마일 쑥 페퍼민트 로즈마리 유칼리투스잎이 들어간 그린 허브 성분이라 피부 진정에도 도움이 되는거 같아요',
  1],
 ['화장품 상자에 한번 더 뽁뽁이  포장으로  꼼꼼하게 담아져 있었고  화장품 용기는 플라스틱 용기인데  용량이 커서  한참 쓸 수 있어 좋네요 뚜껑을 열었을때  향기 좋네 하는 느낌이 없으니 향을 중요시  하는 분은  좋아하지  않을 듯 하네요바르고 조금 시간이 지나면  향이  없어지는 것  같아요용기에 적혀 있는 글씨가 너무 적어  안보였는데 세트 구입했더니 앰플인지 뭔지 모르겠는데  작은 샘플이 개가 있네요  싼 가격에  이 구성이면  좋네요',
  1],
 ['대용량에 헐 감동입니다 개는 지인도 팍팍 쓰라고 선물했어요이건 화장솜에 듬뿍 하셔서 많이 하셔도 흡수는 잘됩니다 저는 얼굴에 흡수가 안되는 타입인데 제품이 흡수 잘되고요 약간의 알콜냄새는 살짝 스치는 정도 입니다 코로나에 다들 든데 이 가격에 정말 감사합니다 마구 쓰시고 싶은 분은 구입 하시고 쫀질한 느낌과 깊은 느낌분들은 살짝 고민하시고 클렌징으로 쓰고 싶다 하시는 분들은 차 쓰시고 고가의 스킨을 바르시는것도 좋을듯 합니다',
  1],
 ['아직 사용전인데 오자마자 간병이모님이 머냐고 물어 보셔서 약쑥스킨이라고  하니 한번 보자고 해서 뚜껑 열어서 향 맞아보고 손에 조금만 부어 보라고 해서 부었더니 발라보시더니 금방 흡수되고 촉촉하다고 하시며 얼마냐고 물어 보셔서 써보시라고 그냥 하나 드렸네요 방에 환자도 뭔데 그리 크냐고 하시면서 어떻게 사냐고 물어보시고 다들 관심 보이네요 각질제거가 된다니 일단 닦토로 써보고 조으면 계속 사서 써보려구요',
  0],
 ['프레쥬 진정토너 여름에 시원하게 토너팩 하기 좋아요 향은 쑥 냄새보다는 시트러스계열 레몬향이 나는 편이구요대용량인데다 이라서 한통은

In [98]:
data_length = len(dataset_all)
train_length = int(data_length*0.6)

dataset_train = dataset_all[0:train_length]
dataset_test = dataset_all[train_length:data_length]
len(dataset_train),len(dataset_test)

(2929, 1953)

In [1]:
!pip install mxnet
!pip install gluonnlp pandas tqdm
!pip install sentencepiece
!pip install transformers
!pip install torch

     |████████████████████████████████| 34.9 MB 1.4 MB/s 
     |████████████████████████████████| 344 kB 1.3 MB/s 
  Created wheel for gluonnlp: filename=gluonnlp-0.10.0-cp38-cp38-macosx_10_9_x86_64.whl size=461641 sha256=e69b0216d0f9c40ea33a0cc92a3529081120b32c6e24a9411b25e86a4249f8c9
  Stored in directory: /Users/icn/Library/Caches/pip/wheels/b6/93/9d/2237550c409eb3ed725d6302b7897ddd9a037b40cef66dcd9c
Successfully built gluonnlp


In [2]:
!pip install git+https://git@github.com/SKTBrain/KoBERT.git@master

  Cloning https://****@github.com/SKTBrain/KoBERT.git (to revision master) to /private/var/folders/b2/zt_25g6x7tdcc_wt2qy0hv600000gn/T/pip-req-build-685syp3g
  Created wheel for kobert: filename=kobert-0.1.2-py3-none-any.whl size=12705 sha256=4a780c2392ba7a141bc45a9e89cbb713dbe3bc205ac131d7e4ade90b2fb4bcf6
  Stored in directory: /private/var/folders/b2/zt_25g6x7tdcc_wt2qy0hv600000gn/T/pip-ephem-wheel-cache-5zoo_j77/wheels/bf/5f/74/81bf3a1332130eb6629ecf58876a8746b77021e7d7b0638e91
Successfully built kobert


In [3]:
import torch
from torch import nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import gluonnlp as nlp
import numpy as np
from tqdm import tqdm, tqdm_notebook

In [4]:
from kobert.utils import get_tokenizer
from kobert.pytorch_kobert import get_pytorch_kobert_model

In [5]:
from transformers import AdamW
from transformers.optimization import get_cosine_schedule_with_warmup

In [7]:
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

[name: "/device:CPU:0"
 device_type: "CPU"
 memory_limit: 268435456
 locality {
 }
 incarnation: 7772285171713691435]

In [8]:
device = torch.device("cpu:0")
device

device(type='cpu', index=0)

In [9]:
bertmodel, vocab = get_pytorch_kobert_model()

[██████████████████████████████████████████████████]
[██████████████████████████████████████████████████]


In [29]:
vocab

Vocab(size=8002, unk="[UNK]", reserved="['[CLS]', '[SEP]', '[MASK]', '[PAD]']")

In [11]:
#!wget https://www.dropbox.com/s/374ftkec978br3d/ratings_train.txt?dl=1
#!wget https://www.dropbox.com/s/977gbwh542gdy94/ratings_test.txt?dl=1

--2021-06-27 14:22:40--  https://www.dropbox.com/s/374ftkec978br3d/ratings_train.txt?dl=1
Resolving www.dropbox.com (www.dropbox.com)... 162.125.80.18
Connecting to www.dropbox.com (www.dropbox.com)|162.125.80.18|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/dl/374ftkec978br3d/ratings_train.txt [following]
--2021-06-27 14:22:41--  https://www.dropbox.com/s/dl/374ftkec978br3d/ratings_train.txt
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc249f29be8bff52f0058603542d.dl.dropboxusercontent.com/cd/0/get/BRNj8wi09R_6yIDIp6JOPcrpmk3qHdL-GCHyWacX-slFtzWmwdBQRC8-Kwx8DBZb29xbpSgfSb9JTBCSXeOWhbCQL5vJ28Bun-MOEfLqAEB5_0U_vi3VUh1LMVgZTUah3gdsvflYN63ovvriCk17ZFHs/file?dl=1# [following]
--2021-06-27 14:22:42--  https://uc249f29be8bff52f0058603542d.dl.dropboxusercontent.com/cd/0/get/BRNj8wi09R_6yIDIp6JOPcrpmk3qHdL-GCHyWacX-slFtzWmwdBQRC8-Kwx8DBZb29xbpSgfSb9JTBCSXeOWhbCQL5vJ28Bun-M

In [12]:
#dataset_train = nlp.data.TSVDataset("ratings_train.txt?dl=1", field_indices=[1,2], num_discard_samples=1)
#dataset_test = nlp.data.TSVDataset("ratings_test.txt?dl=1", field_indices=[1,2], num_discard_samples=1)

In [99]:
dataset_train[:5]

[['쑥 들어간 제품들을 평소에 좋아해서 쑥 화장품으로 대부분 쓰려고 해요 아침 저녁으로 매일 매일 쓰기에 부담이 없고 좋습니다자연약쑥 진정 토너라 자극없이 쓰기에도 좋고 녹차 루이보스 캐모마일 쑥 페퍼민트 로즈마리 유칼리투스잎이 들어간 그린 허브 성분이라 피부 진정에도 도움이 되는거 같아요',
  1],
 ['화장품 상자에 한번 더 뽁뽁이  포장으로  꼼꼼하게 담아져 있었고  화장품 용기는 플라스틱 용기인데  용량이 커서  한참 쓸 수 있어 좋네요 뚜껑을 열었을때  향기 좋네 하는 느낌이 없으니 향을 중요시  하는 분은  좋아하지  않을 듯 하네요바르고 조금 시간이 지나면  향이  없어지는 것  같아요용기에 적혀 있는 글씨가 너무 적어  안보였는데 세트 구입했더니 앰플인지 뭔지 모르겠는데  작은 샘플이 개가 있네요  싼 가격에  이 구성이면  좋네요',
  1],
 ['대용량에 헐 감동입니다 개는 지인도 팍팍 쓰라고 선물했어요이건 화장솜에 듬뿍 하셔서 많이 하셔도 흡수는 잘됩니다 저는 얼굴에 흡수가 안되는 타입인데 제품이 흡수 잘되고요 약간의 알콜냄새는 살짝 스치는 정도 입니다 코로나에 다들 든데 이 가격에 정말 감사합니다 마구 쓰시고 싶은 분은 구입 하시고 쫀질한 느낌과 깊은 느낌분들은 살짝 고민하시고 클렌징으로 쓰고 싶다 하시는 분들은 차 쓰시고 고가의 스킨을 바르시는것도 좋을듯 합니다',
  1],
 ['아직 사용전인데 오자마자 간병이모님이 머냐고 물어 보셔서 약쑥스킨이라고  하니 한번 보자고 해서 뚜껑 열어서 향 맞아보고 손에 조금만 부어 보라고 해서 부었더니 발라보시더니 금방 흡수되고 촉촉하다고 하시며 얼마냐고 물어 보셔서 써보시라고 그냥 하나 드렸네요 방에 환자도 뭔데 그리 크냐고 하시면서 어떻게 사냐고 물어보시고 다들 관심 보이네요 각질제거가 된다니 일단 닦토로 써보고 조으면 계속 사서 써보려구요',
  0],
 ['프레쥬 진정토너 여름에 시원하게 토너팩 하기 좋아요 향은 쑥 냄새보다는 시트러스계열 레몬향이 나는 편이구요대용량인데다 이라서 한통은

In [76]:
dataset_test[:5]

[['굳 ㅋ', '1'],
 ['GDNTOPCLASSINTHECLUB', '0'],
 ['뭐야 이 평점들은.... 나쁘진 않지만 10점 짜리는 더더욱 아니잖아', '0'],
 ['지루하지는 않은데 완전 막장임... 돈주고 보기에는....', '0'],
 ['3D만 아니었어도 별 다섯 개 줬을텐데.. 왜 3D로 나와서 제 심기를 불편하게 하죠??', '0']]

In [14]:
tokenizer = get_tokenizer()
tok = nlp.data.BERTSPTokenizer(tokenizer, vocab, lower=False)

using cached model


In [15]:
class BERTDataset(Dataset):
    def __init__(self, dataset, sent_idx, label_idx, bert_tokenizer, max_len,
                 pad, pair):
        transform = nlp.data.BERTSentenceTransform(
            bert_tokenizer, max_seq_length=max_len, pad=pad, pair=pair)

        self.sentences = [transform([i[sent_idx]]) for i in dataset]
        self.labels = [np.int32(i[label_idx]) for i in dataset]

    def __getitem__(self, i):
        return (self.sentences[i] + (self.labels[i], ))

    def __len__(self):
        return (len(self.labels))

In [100]:
## Setting parameters
max_len = 64
batch_size = 64
warmup_ratio = 0.1
num_epochs = 5
max_grad_norm = 1
log_interval = 200
learning_rate =  5e-5

In [101]:
data_train = BERTDataset(dataset_train, 0, 1, tok, max_len, True, False)
data_test = BERTDataset(dataset_test, 0, 1, tok, max_len, True, False)

In [102]:
train_dataloader = torch.utils.data.DataLoader(data_train, batch_size=batch_size, num_workers=5)
test_dataloader = torch.utils.data.DataLoader(data_test, batch_size=batch_size, num_workers=5)

In [104]:
class BERTClassifier(nn.Module):
    def __init__(self,
                 bert,
                 hidden_size = 768,
                 num_classes=2,
                 dr_rate=None,
                 params=None):
        super(BERTClassifier, self).__init__()
        self.bert = bert
        self.dr_rate = dr_rate
                 
        self.classifier = nn.Linear(hidden_size , num_classes)
        if dr_rate:
            self.dropout = nn.Dropout(p=dr_rate)
    
    def gen_attention_mask(self, token_ids, valid_length):
        attention_mask = torch.zeros_like(token_ids)
        for i, v in enumerate(valid_length):
            attention_mask[i][:v] = 1
        return attention_mask.float()

    def forward(self, token_ids, valid_length, segment_ids):
        attention_mask = self.gen_attention_mask(token_ids, valid_length)
        
        _, pooler = self.bert(input_ids = token_ids, token_type_ids = segment_ids.long(), attention_mask = attention_mask.float().to(token_ids.device))
        if self.dr_rate:
            out = self.dropout(pooler)
        return self.classifier(out)

In [105]:
model = BERTClassifier(bertmodel,  dr_rate=0.5).to(device)

In [106]:
# Prepare optimizer and schedule (linear warmup and decay)
no_decay = ['bias', 'LayerNorm.weight']
optimizer_grouped_parameters = [
    {'params': [p for n, p in model.named_parameters() if not any(nd in n for nd in no_decay)], 'weight_decay': 0.01},
    {'params': [p for n, p in model.named_parameters() if any(nd in n for nd in no_decay)], 'weight_decay': 0.0}
]

In [107]:
optimizer = AdamW(optimizer_grouped_parameters, lr=learning_rate)
loss_fn = nn.CrossEntropyLoss()

In [108]:
t_total = len(train_dataloader) * num_epochs
warmup_step = int(t_total * warmup_ratio)

In [109]:
scheduler = get_cosine_schedule_with_warmup(optimizer, num_warmup_steps=warmup_step, num_training_steps=t_total)

In [110]:
def calc_accuracy(X,Y):
    max_vals, max_indices = torch.max(X, 1)
    train_acc = (max_indices == Y).sum().data.cpu().numpy()/max_indices.size()[0]
    return train_acc

In [112]:
data_train[0]

(array([   2,  517, 6778, 1806, 4158, 5938, 4848, 6896, 4207, 7850,  517,
        6778, 5119, 7078, 1647, 3084, 6061, 4998, 6999, 3130, 3991, 7078,
        1996, 1996, 3084, 5579, 2428, 3271, 4204, 6701, 7147, 6928, 6846,
        6778, 4360, 7227, 4737, 5691, 6003, 3888, 6883, 3084, 5561, 6901,
        4204, 5439, 1494, 7389, 1895, 7096, 6364, 6664, 4643, 6213, 6141,
        7126,  517, 6778, 4829, 7706, 6263, 7659,  517,    3], dtype=int32),
 array(64, dtype=int32),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       dtype=int32),
 1)

In [113]:
data_test[0]

(array([   2, 3942, 6288, 6827, 5703, 2613, 7207, 7116, 4204, 7088, 5377,
        6003,  517, 6266, 6857, 6853, 7096, 1952, 3422, 6779, 5405, 5703,
           3,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
           1,    1,    1,    1,    1,    1,    1,    1,    1], dtype=int32),
 array(23, dtype=int32),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       dtype=int32),
 1)

In [114]:
from tqdm.notebook import tqdm

for e in range(num_epochs):
    train_acc = 0.0
    test_acc = 0.0
    model.train()
    for batch_id, (token_ids, valid_length, segment_ids, label) in enumerate(tqdm_notebook(train_dataloader)):
        optimizer.zero_grad()
        token_ids = token_ids.long().to(device)
        segment_ids = segment_ids.long().to(device)
        valid_length= valid_length
        label = label.long().to(device)
        out = model(token_ids, valid_length, segment_ids)
        loss = loss_fn(out, label)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_grad_norm)
        optimizer.step()
        scheduler.step()  # Update learning rate schedule
        train_acc += calc_accuracy(out, label)
        if batch_id % log_interval == 0:
            print("epoch {} batch id {} loss {} train acc {}".format(e+1, batch_id+1, loss.data.cpu().numpy(), train_acc / (batch_id+1)))
    print("epoch {} train acc {}".format(e+1, train_acc / (batch_id+1)))
    model.eval()
    for batch_id, (token_ids, valid_length, segment_ids, label) in enumerate(tqdm_notebook(test_dataloader)):
        token_ids = token_ids.long().to(device)
        segment_ids = segment_ids.long().to(device)
        valid_length= valid_length
        label = label.long().to(device)
        out = model(token_ids, valid_length, segment_ids)
        test_acc += calc_accuracy(out, label)
    print("epoch {} test acc {}".format(e+1, test_acc / (batch_id+1)))

<ipython-input-114-e6a38b13095b>:5: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch_id, (token_ids, valid_length, segment_ids, label) in enumerate(tqdm_notebook(train_dataloader)):


KeyboardInterrupt: 